@extends('appAdmin')

@section('page-styles')
<style type="text/css">
            .presenttipstab{
                text-decoration:underline;
                font-weight:bold;	
            }
	</style>
@endsection

@section('page-scripts')
	
@endsection

@section('content')

<div class="row">
	<div class="col-sm-12">
		<div class="row">
			<div class="col-sm-9">
     		 <h2 class="page-head" style="color:rgb(0,90,170)">Presentation Tips and Pearls of Wisdom</h2>
			   <div style="border:3px solid rgb(0,82,165);">
            </div>
			 <br />
			<p>Since cost savings and free equipment tend to be logical sales points, and we all know that 
			sales are based on emotion, so we need to approach some tips and ideas to use the emotional 
			services to connect the merchant to the close. Emotional points purposely built into the presentation 
			are the trial closes, the &#8220;Scooby Doo Question&#8221;, and the final 2 service segments, Private 
			Label Merchant Cards and Affinity, because they can <strong><span style="text-decoration: underline;">
			make</span></strong> money with them.</p>
			<br />
			<p>The Private Label Merchant Card is limited only to your imagination and you need to use it (both 
			the program and your imagination) each and every time you present <span style="text-decoration: underline;"><strong>with 
			passion and belief.</strong></span> Here are a few ideas to get your imagination flowing:</p>
			<br />
			<p><strong>1. <span style="text-decoration: underline;color:rgb(0,90,170)">Pizza (or other) Restaurant</span></strong> &#8211; <em>&#8220;Tony, if you took just 30 of your first 50 cards we help you set up and use with your business name, address, number and motto of your business on them. I will help you load them with $5 of value that can only be redeemed in your business and you have a delivery guy take them down to the local High School football game. As the game let&#8217;s out, picture him standing there with a Tony&#8217;s Pizzeria shirt on and a big ol&#8217; pizza hat on. As the crowd goes by, he passes out the cards sporadically &#8220;Tony&#8217;s Pizzeria! Best Slice In Town! Five dollars off your first order! Here you go, sir.&#8221; And he passes them out to a few high school kids, a few families of four and a few elderly couples. Now Tony, there are </em>now <em>30 five dollar reasons to come to your restaurant at least once in the hands of your target market. So how many of those cards do you suppose will come back into your front door, say, in the next 30 to 60 days?</em> (Wait for the answer, most will say &#8220;All&#8221; or &#8220;Most&#8221;). <em>Tony, I agree, but let&#8217;s cut that in half and say just 15 come back in. That&#8217;s 15 new customers, with an average ticket of $30, so let&#8217;s call it $25 with the discount. That&#8217;s no less than $375 of new business into your door in less than 30 days. But is your food or service good enough to get them to come back? </em>(Again, wait for the answer which should be &#8220;yes&#8221;) <em>Ok, so when you take the card and swipe it for the $5.00 off the ticket, you smile and say &#8220;This is now your Chef&#8217;s Club Card. Bring this back each visit and on your 5th visit, you will get $10 off of your order.&#8221; And you now simply load it as a loyalty card by swiping it once more. With that working, between your food, service and a monetary reason to come back, how many of those new customers you suppose will be coming back at least monthly? </em>(The answer will be &#8220;most&#8221;) <em>Well Tony, let&#8217;s say half again. So what you are telling me</em> (His words are better than yours)<em> is that this program alone can bring in $375 of new revenue monthly and in addition, should bring another $200 of monthly repeat revenue which multiplies every month you use it. Just after 6 months, your revenues could easily increase by $1200 per month, not including the $375. What colors did you want those cards printed in?&#8221;</em></p>
			<br />
			<p><strong>2. <span style="text-decoration: underline;color:rgb(0,90,170)"> Auto Repair</span></strong> - <em>&#8220;Bob, I understand that no one is going to walk in here looking for a gift card, but they also are not just going to simply walk in here without a reason. Right now, the only reason is because they need your service and either someone told them about you and the good, honest work you do, or they tripped over you by accident in the Yellow Pages or online. What if you could increase those odds two fold and not have to rely on someone else or pure chance to get good work into your front door? </em>(Wait for the response)<em> Let me give you a few ways we can drive new customers to you. First, we understand that an oil change is a loss leader for most garages. Doesn&#8217;t cost much, doesn&#8217;t make much, but it pulls them in. So imagine if every Driver&#8217;s Ed course at the local High Schools and the private courses as well issued a &#8216;Bob&#8217;s Auto Repair Safe Maintenance Card&#8217; to their students for a 50% off oil and lube on their first visit with their completion certificate. 85% of issued value cards are redeemed by the person that received it, so you are not just attacking a new market your competition hasn&#8217;t even thought of, but you are reaching out and touching some of those parents, also. Every one of those courses preaches to maintain their vehicle safely. They don&#8217;t teach it, but preach it. So by donating these cards to them, you earn good will and great new revenue. Once the card comes in, you reload it as their &#8216;Loyal Luber&#8217; card and by using it at your business, the 5th oil change is free. Now you have them with a reason to come back to you exclusively, which is customer loyalty and loyal revenue. The average garage can increase their revenues by 35% to 50% just in the initial response, but if they come in, will your service and talent bring them back? Now, what colors do you think would best show your company on the cards?&#8221;</em></p>
			<br />
			<p><strong>3. <span style="text-decoration: underline;color:rgb(0,90,170)">Craft/Gift/Bead/Quilt/Sewing/Scrapbooking Shops (also good for Bowling Alleys, Game Arcades, Pizza Places, etc)</span></strong> - <em>&#8220;Carol, your type of shop is built around loyalty and a specific pool of customers. Many tell me they know who is coming in their shop before the door even opens, and that is such a great thing to have. My question is if you could double that pool of loyal customers, what would that do to your bottom line? </em>(Wait for the response) <em>You see, there is a market for you that do not know you are here for them, and we uncovered it awhile back somewhat by accident. A bead shop we had set up with a simple gift card program asked to cancel it as so few people had came in and purchased one. In a last thought, my daughter&#8217;s birthday was coming up, so I asked to put $5 of value on 19 of their cards, placed them in the envelopes, and put them in my daughter&#8217;s &#8216;gift bags&#8217; for her birthday at the daycare with a little note explaining the bead shop for necklaces, bracelets, etc for the kids or their dolls. Within 30 days, 17 of the 19 cards came into the shop, with an average $37 purchase and 5 parents asked if they could set up birthday bead party for their kids at the shop. Without even knowing it, a tremendous market was living right there, but just did not have an idea or reason to walk through the front door. Kids bring parents and the business and revenue expanded from there. Needless to say, with hundreds of gift and loyalty cards issued and distributed, along with the new birthday and doll party schedule, they are no longer considering turning off that revenue engine. Can you see how this can be an equally, or even similar positive impact on your bottom line? I noticed your sign was gold and green. I think those colors would be perfect for your cards, but do you want the gold card with green lettering or green card with gold lettering?&#8221;</em></p>
			<br />
			<p><strong>4. <span style="text-decoration: underline;color:rgb(0,90,170)">Auto Body Shop, Residential Fencing, Siding, ect</span></strong> - <em>&#8220;Bob, let&#8217;s face it, when anyone gets in an accident or something happens to their car, there are really only three things on their mind. Is it going to look as good, or better, than it did before? How long is it going to take because I have to deal with a rental? And how much is it going to cost me? Since most people still like to get several estimates, let&#8217;s use 3. If I go to Body Shop A and B and they tell me I have $2500 worth of damage, they both tell me they do great work and I have a 4 to 5 day turn around and it is going to cost me my $500 deductible, I can assume they are close. Then I come walking into your shop. Say it is right at $2500 of damage. DO you do good work? </em>(Let them answer)<em> Ok, then what is an average turn-around as long as you don&#8217;t have to wait for any parts needed? </em>(Let them answer)<em> So what you&#8217;re saying is from a consumer&#8217;s eye, like mine, there is not a big difference? But when I ask you how much is it going to cost, you grab a card with your business name, address, phone number and motto on it, swipe it through your credit card terminal, hand it to me and say, &#8220;Mike, this is our guaranteed estimate and warranty card. You bring this back to me and it is worth $150 off of your deductible.&#8221; Now where do you suppose I am going to be motivated to go to? I also know that the insurance companies, to stay certified, require you to collect the deductible, but they cannot deem how you collect it. So cash, check, credit card or stored value card is irrelevant. You will have a receipt for $500 of payment from your credit card machine and a new customer in the bank. How much is 3 or 5 new jobs a month worth to your bottom line?&#8221;</em></p>
			<br />
			<p><strong>5. <span style="text-decoration: underline;color:rgb(0,90,170)">Hair Salon, Spa, Nail Salon, etc</span></strong> - <em>&#8220;Carol, services like yours are very unique. You have those loyal customers who you can almost know the exact day and time they will walk in, and have forever, and then you have those drop ins, new clients that you may or may not ever see again. What if you could significantly increase both of those groups, and increase the odds of repeat visits by the ones that don&#8217;t right now? </em>(Most won&#8217;t answer the question but give you the &#8216;I&#8217;m listening&#8217; comment or look)<em> You count on word of mouth, like every other salon. But like my wife </em>(or me)<em>, when I get my hair </em>(nails, pedi, facial)<em> done, someone will always comment within the first few days. Of course my wife responds &#8220;Yes, Carol over at Salon de Lux is spectacular, you should try her.&#8221; The problem is that 2 or 3 days later, the comment and Carol are forgotten, and that person will go back where they have before, which is an opportunity missed. But let&#8217;s say you gave my wife a professional imaged Gift Card with your business name, address, phone number and motto on it. Heck, with a Sharpie put her initials on the back in the corner and ask her, &#8220;Lori, the first person that comments on your hair, could you give them this card and tell them who takes care of you? For being such a loyal customer, when it comes back in, your referral will get 15% off any service, and after it comes in, you re-swipe it and load it as that new customer&#8217;s &#8216;Loyal Luxury&#8217; card, and say, as a welcome, bring this card in and on your fifth visit, you get an additional 15% off. Now you are incenting repeat business and creating yet another client who can work your marketing referral card system for you. Don&#8217;t you think it is about time your business started working for you?</em></p>
			<br />
			<p>As you notice, many of the above ideas are not the traditional gift card thought patterns. The merchant has already thought of those and if they do not have a program, if they have decided against it for a reason or two. You have to bring a new game to their table that they can see as fresh and not a hassle to implement. You have to paint the picture that they can see money from it. Remember, it is all in the presentation. You can have the best tasting steak in town, but if you serve it on a garbage can lid, it is not very appetizing. As an income increaser, your imagination is one of your best tools, so do not wait for others to give you ideas to increase your income, because that is your job. Your RSSM is a wealth of information in this area, so pick their brain. But do not just count on their imagination, engage yours in full gear.</p>
			 
		</div>
	</div>
</div>

@endsection
